2019-10-09 15:21:41,556 ERROR: Exception on /index [GET] [in /scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/scratch/knerr/repos/mydrop/mytrilog/app/routes.py", line 33, in index
    return render_template('index.html', title='Home', form=form, workouts=workouts)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/scratch/knerr/repos/mydrop/mytrilog/app/templates/index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/scratch/knerr/repos/mydrop/mytrilog/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/scratch/knerr/repos/mydrop/mytrilog/app/templates/index.html", line 10, in block "content"
    {{ form.post.label }}<br>
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.WorkoutForm object' has no attribute 'post'
2019-10-09 15:22:51,464 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-09 15:22:55,011 ERROR: Exception on /index [GET] [in /scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/scratch/knerr/repos/mydrop/mytrilog/app/routes.py", line 33, in index
    return render_template('index.html', title='Home', form=form, workouts=workouts)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/scratch/knerr/repos/mydrop/mytrilog/app/templates/index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/scratch/knerr/repos/mydrop/mytrilog/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/scratch/knerr/repos/mydrop/mytrilog/app/templates/index.html", line 10, in block "content"
    {{ form.workout.label }}<br>
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.WorkoutForm object' has no attribute 'workout'
2019-10-09 15:24:56,802 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-09 15:26:41,705 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-09 15:29:01,303 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-09 15:30:09,956 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-09 15:34:37,422 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-09 15:39:08,831 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-09 15:41:55,084 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-09 15:45:05,609 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-09 15:55:57,276 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-09 15:58:46,093 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-09 15:59:08,132 ERROR: Exception on /explore [GET] [in /scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/scratch/knerr/repos/mydrop/mytrilog/app/routes.py", line 136, in explore
    workouts = Workout.query.order_by(Workout.timestamp.desc()).all()
AttributeError: type object 'Workout' has no attribute 'timestamp'
2019-10-09 15:59:37,258 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-10 10:39:00,553 INFO: MyTriLog startup... [in /home/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-10 10:39:05,920 INFO: MyTriLog startup... [in /home/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-12 11:49:26,384 INFO: MyTriLog startup... [in /home/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-12 11:55:11,742 INFO: MyTriLog startup... [in /home/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-12 12:13:15,540 INFO: MyTriLog startup... [in /home/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-12 12:14:30,449 INFO: MyTriLog startup... [in /home/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-12 12:14:42,245 INFO: MyTriLog startup... [in /home/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-12 12:18:17,646 INFO: MyTriLog startup... [in /home/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-12 12:30:04,844 INFO: MyTriLog startup... [in /home/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-12 12:38:40,203 INFO: MyTriLog startup... [in /home/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-12 12:43:32,491 INFO: MyTriLog startup... [in /home/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-12 13:38:26,672 INFO: MyTriLog startup... [in /home/knerr/repos/mydrop/mytrilog/app/__init__.py:45]
